---
- name: Setup the Sites within NETBOX
  netbox.netbox.netbox_site:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ obtained_token }}"
    data: "{{ site }}"
    state: "{{ install_state }}"
  register: site_setup
  loop: "{{ sites }}"
  loop_control:
    loop_var: site
    label: "{{ site.name }}"
  tags: [sites, devices]
