---
- name: Setup the Platforms within NETBOX
  netbox.netbox.netbox_platform:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ obtained_token }}"
    data:
      name: "{{ platform.name }}"
      slug: "{{ platform.slug }}"
    state: "{{ install_state }}"
  loop: "{{ platforms }}"
  loop_control:
    loop_var: platform
    label: "{{ platform['name'] }}"
  tags: [devices]
