---
- name: Setup the Device Roles within NETBOX
  netbox.netbox.netbox_device_role:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ obtained_token }}"
    data:
      name: "{{ device_role.name }}"
      slug: "{{ device_role.slug }}"
      color: "{{ device_role.color }}"
      vm_role: "{{ device_role.vm_role }}"
    state: "{{ install_state }}"
  loop: "{{ device_roles }}"
  loop_control:
    loop_var: device_role
    label: "{{ device_role['name'] }}"
  tags: [devices]
