---
- name: Setup the Manufacturers within NETBOX
  netbox.netbox.netbox_manufacturer:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ obtained_token }}"
    data:
      name: "{{ manufacturer }}"
    state: "{{ install_state }}"
  register: manufacturer_setup
  loop: "{{ manufacturers }}"
  loop_control:
    loop_var: manufacturer
  tags: [devices]
