---
- name: Combine all gathered outputs into a single variable
  ansible.builtin.set_fact:
    eos_output:
      device: "{{ device_output }}"
      eos_facts: "{{ eos_facts_output }}"
      eos_acl_interfaces: "{{ eos_acl_interfaces_output }}"
      eos_acls: "{{ eos_acls_output }}"
      eos_bgp_global: "{{ eos_bgp_global_output }}"
      eos_command: "{{ eos_command_output }}"
      eos_config: "{{ eos_config_output }}"
      eos_eapi: "{{ eos_eapi_output }}"
      eos_hostname: "{{ eos_hostname_output }}"
      eos_interfaces: "{{ eos_interfaces_output }}"
      eos_l2_interfaces: "{{ eos_l2_interfaces_output }}"
      eos_l3_interfaces: "{{ eos_l3_interfaces_output }}"
      eos_lacp: "{{ eos_lacp_output }}"
      eos_lacp_interfaces: "{{ eos_lacp_interfaces_output }}"
      eos_lag_interfaces: "{{ eos_lag_interfaces_output }}"
      eos_lldp_global: "{{ eos_lldp_global_output }}"
      eos_logging: "{{ eos_logging_output }}"
      eos_logging_global: "{{ eos_logging_global_output }}"
      eos_ntp_global: "{{ eos_ntp_global_output }}"
      eos_ospf_interfaces: "{{ eos_ospf_interfaces_output }}"
      eos_ospfv2: "{{ eos_ospfv2_output }}"
      eos_ospfv3: "{{ eos_ospfv3_output }}"
      eos_prefix_lists: "{{ eos_prefix_lists_output }}"
      eos_route_maps: "{{ eos_route_maps_output }}"
      eos_snmp_server: "{{ eos_snmp_server_output }}"
      eos_system: "{{ eos_system_output }}"
      eos_vlans: "{{ eos_vlans_output }}"
