---
- name: Setup the WWT CUSTOM FIELDS within NETBOX
  netbox.netbox.netbox_custom_field:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ obtained_token }}"
    data:
      name: "{{ custom_field.name }}"
      type: "{{ custom_field.type }}"
      label: "{{ custom_field.label }}"
      description: "{{ custom_field.description }}"
      ui_visibility: "{{ custom_field.ui_visibility }}"
      content_types: "{{ custom_field.content_type }}"
      group_name: "{{ custom_field.group_name }}"
    state: "{{ install_state }}"
  loop: "{{ custom_fields }}"
  loop_control:
    loop_var: custom_field
    label: "{{ custom_field['name'] }}"
  tags: [devices]
