---
ansible_host: 192.168.5.111
ansible_network_os: arista.eos.eos
ansible_become: true
ansible_become_method: enable
switch_username: ansible
switch_password: ansible
ansible_connection: network_cli

# Netbox device variables
netbox_variables:
  - name: "AristaSwitch"
    airflow: "front-to-rear"
    asset_tag: ""
    cluster: ""
    comments: ""
    custom_fields: ""
    description: "Arista Lab Switch"
    device_role: "Router"
    device_type: "vEOS"  # dynamic
    face: "Front"
    location: ""
    platform: "EOS"  # dynamic
    position: "40"
    primary_ip4: "172.19.0.5/24"  # dynamic
    primary_ip6: ""
    rack: "CHI_01"
    serial: ""  # dynamic
    site: "CHI"
    status: "Active"
    tags: "Access"
    tenant: ""

# WWT Custom Fields
wwt_fields:
  - WWT_Device_ID: "#00004532"
    EOL_date: "2026-12-31"  # must be a date
    EOS_date: "2024-12-31"  # must be a date
    WWT_Purchase_Order: "PO-00345265"
    Device_Cost: "$25,600"
    Install_Date: "2020-01-01"  # must be a date
    Replace_Date: "2024-01-31"  # must be a date
    sw_ver: "1111"
